### ISSUE TITLE
Selection should be deleted when typing

### ISSUE THREAD

**Issue by trmdi** [fcitx/fcitx5-unikey#10]
I remember on fcitx4 when you're selecting a text then type, the selection will be removed.
But in fcitx5 it doesn't work like that it should.

![image](https://user-images.githubusercontent.com/11857205/141404941-5817ade4-d358-40e7-9ba8-81bd991db9f3.png)

**Comment by trmdi** [comment]
This happens on Kate but not on Firefox.

**Comment by wengxt** [comment]
I just test it, it's exact same. When preedit is used, the selection will be replaced only after commit string happens.

**Comment by trmdi** [comment]
> I just test it, it's exact same. When preedit is used, the selection will be replaced only after commit string happens.

The selection should be removed right after you type the first character "g" without committing.
Do you mean it works like I expect on your Kate ?

**Comment by trmdi** [comment]
Here are some videos:
1, Kate (not expected)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/11857205/141603230-25d943d5-29ed-445b-842c-cccccb1fa160.gif)
2, Dolphin (should be like this
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/11857205/141603228-75f19d02-fc7a-41bd-86ac-71f73ced621c.gif)
)

**Comment by wengxt** [comment]
I’m saying it’s same for fcitx4/5, not saying it’s different from your case.

The behavior is mainly implementation defined in different toolkit.

kate implementation is not regular qt widget, but it’s own widget, so it’s not a surprise that they behave differently.

**Comment by trmdi** [comment]
> I’m saying it’s same for fcitx4/5,

Ah, sorry about that. My bad.

**Comment by wengxt** [comment]
I sent a PR to ktexteditor.

https://invent.kde.org/frameworks/ktexteditor/-/merge_requests/225
