### ISSUE TITLE
Use surrounding text to detect context.

### ISSUE THREAD

**Issue by wengxt** [fcitx/fcitx5-unikey#12]

**Comment by wengxt** [comment]
For the issue described in #6.

When reset is called, the buffer is cleared. We should try to restore the key history from surrounding text. The same techniques is also used by fcitx5-chinese-addons's punctuation module.

**Comment by wengxt** [comment]
@Nekosha Please give it a try and let me know if there's any problem.

**Comment by Nekosha** [comment]
Seems to be working well. I've been using it for 2 weeks with no problems.
Cheers!
