### ISSUE TITLE
Problem switch to Unikey in some applications?

### ISSUE THREAD

**Issue by hoangnnh** [fcitx/fcitx5-unikey#14]
I can write Vietnamese in apps likes Chrome or Vscode, but some apps such as WPS or Terminal, i'm unable to switch and write in Unikey.

**Comment by shadichy** [comment]
cùng trường hợp

**Comment by wengxt** [comment]
I don't see a problem with WPS actually. What you might need is to press Ctrl + Alt + P to disable clients side preedit.

As for terminal, which Terminal is that? I don't think common terminal like gnome-terminal / xterm / konsole / etc would have a problem, especially when you say can't switch to unikey. That sounds more like the key event does not reach fcitx. That's more likely to be a configuration issue.

You may want to run fcitx5-diagnose to check the setup. We could help take a look if you post the output here.

See also: https://fcitx-im.org/wiki/Setup_Fcitx_5

**Comment by trmdi** [comment]
@shadichy 
This is an international project so please use English.

**Comment by trmdi** [comment]
@wengxt 

Is it possible to improve the WPS case since now it uses Qt5 ?
The issue with it is that the preedit is not updated until you commit it.

**Comment by hoangnnh** [comment]
I uninstall all the fcitx related-packages and reinstall. Then everything works fine! But I can't still remove the underline.

**Comment by hoangnnh** [comment]
> I don't see a problem with WPS actually. What you might need is to press Ctrl + Alt + P to disable clients side preedit.
> 
> As for terminal, which Terminal is that? I don't think common terminal like gnome-terminal / xterm / konsole / etc would have a problem, especially when you say can't switch to unikey. That sounds more like the key event does not reach fcitx. That's more likely to be a configuration issue.
> 
> You may want to run fcitx5-diagnose to check the setup. We could help take a look if you post the output here.
> 
> See also: https://fcitx-im.org/wiki/Setup_Fcitx_5

Thanks for helping me turn off the preedit feature 🥰

**Comment by wengxt** [comment]
> @wengxt
> 
> Is it possible to improve the WPS case without disabling client side preedit, since now it uses Qt5 ? The issue with it is that the preedit is not updated until you commit it.

Well WPS is definitely using custom qt widget, so it need to write their own support for preedit. It has nothing to do with Qt5 or not. I actually gonna send them a email to indicates if they don't have plan to support it properly, at least they should declare that preedit is not supported.

**Comment by wengxt** [comment]
> I uninstall all the fcitx related-packages and reinstall. Then everything works fine! But I can't still remove the underline.

Ah, you're right, I shouldn't use underline in the input popup window.

**Comment by wengxt** [comment]
In next version of fcitx5, wps will be in a blacklist for disabling preedit by default. I'll close this for now.
