### ISSUE TITLE
More modes?

### ISSUE THREAD

**Issue by shadichy** [fcitx/fcitx5-unikey#15]
Tôi thấy bên ibus-bamboo có khá nhiều input mode cho phép chuyển đổi qua lại để capable với 1 số các software trong trường hợp default không hoạt động

**Comment by shadichy** [comment]
à mấy ông sửa luôn lỗi khi nhập ưoi đi nha, nó bị v nè: ngừoi ưoi

**Comment by wengxt** [comment]
I don't really care about ibus-bamboo approach. Especially many of them are really hacky and can't work in general for Wayland. If you have any problem with certain application, you might want to create a separate issue and we can see if we could fix it with upstream.

**Comment by shadichy** [comment]
if so, fix 'ưoi
'
