### ISSUE TITLE
Nix/Nixos support?

### ISSUE THREAD

**Issue by langbamit** [fcitx/fcitx5-unikey#17]
`fcitx5-chinese-addons`, `fcitx5-rime`, `fcitx5-mozc` already listed on https://search.nixos.org/packages. Any plan for this?

**Comment by CoelacanthusHex** [comment]
May it be duty of NixOS packagers instead of developer of Fcitx.

**Comment by berberman** [comment]
Added: https://github.com/NixOS/nixpkgs/pull/154699

**Comment by wengxt** [comment]
Not really a issue for fcitx project. We don't do any downstream packaging.
