### ISSUE TITLE
Issue #12 is not fully resolved.

### ISSUE THREAD

**Issue by Nekosha** [fcitx/fcitx5-unikey#19]
**Describe the bug**
Commit [@437581a](https://github.com/fcitx/fcitx5-unikey/commit/437581a9b41eedaf729aba8a1e547edf3458ceba) is incomplete. 
When surrounding text detects a valid sequence that may modify the already commited text, the new text is inserted.

**To Reproduce**
1. Use a text editor. Chrome seems to ignore this.
2. Type `ang`
3. Move the cursor back one character, between `n` and `g`
4. Type `a`. Surrounding text detects sequence `an` and tries to rebuild as `ana` = `ân`
5. `ân` gets inserted. Resulting text `anâng`.

<details>
<summary>
Running fcitx5 with loglevel debug
</summary>

```
D2022-04-16 09:03:38.298815 instance.cpp:2280] Instance::activateInputMethod
D2022-04-16 09:03:38.298889 instance.cpp:2285] Activate: [Last]: [Activating]:unikey
D2022-04-16 09:03:38.301597 instance.cpp:2372] Input method switched
D2022-04-16 09:03:38.368488 xim.cpp:87] -- XIM_SET_IC_VALUES
D2022-04-16 09:03:38.368536 xim.cpp:517] XIM header opcode: 54
D2022-04-16 09:03:38.368778 xim.cpp:122] XIM filtered event
D2022-04-16 09:03:40.067512 instance.cpp:1030] KeyEvent: Key(a states=0) rawKey: Key(a states=0) origKey: Key(a s
tates=0) Release:0
D2022-04-16 09:03:40.169618 instance.cpp:1030] KeyEvent: Key(a states=0) rawKey: Key(a states=0) origKey: Key(a s
tates=0) Release:1
D2022-04-16 09:03:40.199664 instance.cpp:1030] KeyEvent: Key(n states=0) rawKey: Key(n states=0) origKey: Key(n s
tates=0) Release:0
D2022-04-16 09:03:40.281451 instance.cpp:1030] KeyEvent: Key(n states=0) rawKey: Key(n states=0) origKey: Key(n s
tates=0) Release:1
D2022-04-16 09:03:40.331257 xim.cpp:87] -- XIM_SET_IC_VALUES
D2022-04-16 09:03:40.331304 xim.cpp:517] XIM header opcode: 54
D2022-04-16 09:03:40.331507 xim.cpp:122] XIM filtered event
D2022-04-16 09:03:40.331614 instance.cpp:1030] KeyEvent: Key(g states=0) rawKey: Key(g states=0) origKey: Key(g s
tates=0) Release:0
D2022-04-16 09:03:40.433848 xim.cpp:87] -- XIM_SET_IC_VALUES
D2022-04-16 09:03:40.433952 xim.cpp:517] XIM header opcode: 54
D2022-04-16 09:03:40.434472 xim.cpp:122] XIM filtered event
D2022-04-16 09:03:40.434694 instance.cpp:1030] KeyEvent: Key(g states=0) rawKey: Key(g states=0) origKey: Key(g s
tates=0) Release:1
D2022-04-16 09:03:41.229714 instance.cpp:1030] KeyEvent: Key(Left states=0) rawKey: Key(Left states=0) origKey: K
ey(Left states=0) Release:0
D2022-04-16 09:03:41.321240 instance.cpp:1030] KeyEvent: Key(Left states=0) rawKey: Key(Left states=0) origKey: K
ey(Left states=0) Release:1
D2022-04-16 09:03:41.321422 unikey-im.cpp:189] Rebuild surrounding with: an
D2022-04-16 09:03:42.640840 xim.cpp:87] -- XIM_SET_IC_VALUES
D2022-04-16 09:03:42.640925 xim.cpp:517] XIM header opcode: 54
D2022-04-16 09:03:42.641425 xim.cpp:122] XIM filtered event
D2022-04-16 09:03:42.641533 instance.cpp:1030] KeyEvent: Key(a states=0) rawKey: Key(a states=0) origKey: Key(a s
tates=0) Release:0
D2022-04-16 09:03:42.641707 inputcontext.cpp:238] KeyEvent handling time: 0ms result:1
D2022-04-16 09:03:42.711241 xim.cpp:87] -- XIM_SET_IC_VALUES
D2022-04-16 09:03:42.711291 xim.cpp:517] XIM header opcode: 54
D2022-04-16 09:03:42.711674 xim.cpp:122] XIM filtered event
D2022-04-16 09:03:42.711779 instance.cpp:1030] KeyEvent: Key(a states=0) rawKey: Key(a states=0) origKey: Key(a s
tates=0) Release:1
D2022-04-16 09:03:42.711902 inputcontext.cpp:238] KeyEvent handling time: 0ms result:0
D2022-04-16 09:03:49.376222 xim.cpp:87] -- XIM_SET_IC_VALUES
D2022-04-16 09:03:49.376310 xim.cpp:517] XIM header opcode: 54
D2022-04-16 09:03:49.377832 xim.cpp:122] XIM filtered event
```
</details>

**Expected behavior**
One of the following is expected:
1. `âng` (`an` is replaced with `ân`)
2. `anag` (does not use surrounding text if it needs to modify already commited sequence).

**Desktop (please complete the following information):**
 - Desktop: none
 - Display server type: X11
 <details>
  <summary>Output of fcitx5-diagnose:</summary>

  # System Info:
1.  `uname -a`:

        Linux unknown-host 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:55:33 +0000 x86_64 GNU/Linux

2.  `lsb_release`:

    `lsb_release` not found.

3.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

4.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        LOGO=archlinux-logo

5.  Desktop Environment:

    Cannot determine desktop environment.

6.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

7.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete+japan"	};
            	xkb_symbols   { include "pc+jp(OADG109A)+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc104)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc106", "jp", "OADG109A", ""

3.  Locale:

    1.  All locales:

            C
            POSIX
            en_US.utf8
            vi_VN.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE=en_US.UTF-8
            LC_NUMERIC="en_US.UTF-8"
            LC_TIME="en_US.UTF-8"
            LC_COLLATE=C
            LC_MONETARY=en_US.UTF-8
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER=en_US.UTF-8
            LC_NAME=en_US.UTF-8
            LC_ADDRESS=en_US.UTF-8
            LC_TELEPHONE=en_US.UTF-8
            LC_MEASUREMENT=en_US.UTF-8
            LC_IDENTIFICATION=en_US.UTF-8
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/1000

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/1000/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/1000/.config/fcitx5`).

5.  Current user:

    The script is run as 1000 (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.15`

3.  process:

    Found 1 fcitx5 process:

          20813 fcitx5

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.145`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `20813`.

    Debug information from dbus:

           Group [x11::0] has 9 InputContext(s)
          IC [2289ec994bd04b009ab752071a1a9e86] program:gedit frontend:dbus cap:6000000012 focus:0
          IC [69b87918028b45898519f39a8d52d81f] program:gedit frontend:dbus cap:6000000012 focus:0
          IC [5363cf6ddffc4d0c80446ba5047bbd3f] program:gedit frontend:dbus cap:6000000012 focus:0
          IC [a67d6fcebb2d4e16a69f40f8be0d601b] program:gedit frontend:dbus cap:6000000052 focus:0
          IC [100825a4c68045daadc374c953a5194a] program:gedit frontend:dbus cap:6000000012 focus:0
          IC [8457e56c34924fe39573e906b0883586] program:gedit frontend:dbus cap:6000000012 focus:0
          IC [266eb08e16934e9d8592afe1d7e0b2e2] program:gedit frontend:dbus cap:6000000012 focus:0
          IC [3efbb7b353c449009a75791e34a0939b] program:gedit frontend:dbus cap:6000000012 focus:0
          IC [098b2ac811fc42e6ad6e0ba767650282] program:alacritty frontend:xim cap:4000000000 focus:1
        Input Context without group
# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found unknown fcitx qt module: `/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`.
    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx5-unikey-macro-editor.so`.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.33` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.33

        Found fcitx5 im modules for gtk `3.24.33`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    2.  gtk 3:

        Found immodules cache for gtk `3.24.33` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.33

        Found fcitx5 im modules for gtk `3.24.33`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 14 enabled addons:

            Classic User Inteface 5.0.15
            Clipboard 5.0.15
            DBus 5.0.15
            DBus Frontend 5.0.15
            Emoji 5.0.15
            Input method selector 5.0.15
            Keyboard 5.0.15
            Mozc
            Status Notifier 5.0.15
            Notification 5.0.15
            Unicode 5.0.15
            Unikey Wrapper For Fcitx 5.0.9
            XCB 5.0.15
            X Input Method Frontend 5.0.15

    2.  Found 7 disabled addons:

            Fcitx4 Frontend 5.0.15
            IBus Frontend 5.0.15
            KDE Input Method Panel 5.0.15
            Quick Phrase 5.0.15
            Spell 5.0.15
            Wayland 5.0.15
            Wayland Input method frontend 5.0.15

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 1 enabled user interface addons:

        Classic User Inteface

## Input Methods:
1.  `~/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Main
        # Layout
        Default Layout=jp-OADG109A
        # Default Input Method
        DefaultIM=unikey

        [Groups/0/Items/0]
        # Name
        Name=keyboard-jp-OADG109A
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=unikey
        # Layout
        Layout=jp-OADG109A

        [Groups/0/Items/2]
        # Name
        Name=mozc
        # Layout
        Layout=jp-OADG109A

        [GroupOrder]
        0=Main

# Log:
1.  `date`:

        2022/4/16 Sat 08:51:10 +02

2.  `~/.config/fcitx5/crash.log`:

    `~/.config/fcitx5/crash.log` not found.
 </details>

**Comment by wengxt** [comment]
This is expected and that's why this is an option instead of an always-on option. There's no way we could distinguish when you want to modify, or continue to type.

I'd really hope firefox could be fixed instead of rely on this option as a workaround.
