### ISSUE TITLE
How to use user-defined input method?

### ISSUE THREAD

**Issue by 0xReki** [fcitx/fcitx5-unikey#20]
I can't seem to find the place to edit user-defined input method. This seems to be missing from any unikey implementation for linux.

**Comment by wengxt** [comment]
@0xReki What functionality are you actually talking about? Are you talking about the macro?

**Comment by 0xReki** [comment]
No, not macro, but user-defined alternative input method like VNI, VIQR, etc.
There is the option UserIM in the configuration tool, but no place to configure said UserIM.
![Screenshot_2022-05-18_12-18-51](https://user-images.githubusercontent.com/6464463/169016888-4b48bd66-fe6e-45ea-8d76-79dfd72d5bac.png)

I already have a configuration file, so just knowing where to put it, so https://github.com/fcitx/fcitx5-unikey/blob/master/unikey/usrkeymap.cpp can parse it, would already be helpful.

An UI for creating that file, would be better. Here's a screenshot of the editor of the Windows UniKey tool.
![Screenshot_2022-05-18_12-12-56](https://user-images.githubusercontent.com/6464463/169016076-e2f0c6b8-359a-4b80-8e3c-3f2c90c07936.png)

**Comment by wengxt** [comment]
With the latest git, you should be able to load user keymap from ~/.config/fcitx5/unikey/keymap.txt .

I'll add an keymap editor as the next step.

**Comment by 0xReki** [comment]
Thanks. It works like as expected.

Btw, you have make sure the file uses unix style new lines. Importing an existing file from Windows with Windows style new lines will result in parsing errors: "Error in user key layout, line xx: command not found".

**Comment by wengxt** [comment]
Thanks for the heads up. The latest git should be fine with both line endings.

**Comment by wengxt** [comment]
I added the keymap editor in the latest commit, feel free to give it a try.
