### ISSUE TITLE
Option to hide underline for preedit by default for all Vietnamese input methods

### ISSUE THREAD

**Issue by zenfas** [fcitx/fcitx5-unikey#22]
Vietnamese has a little different from Chinese or Japanese, on Windows with Unikey or Android with Laban Key, we don't have underline. So when people come to Linux, most of people don't like underline when we're typing. If can, please hide it by default. Thank you.

**Comment by trmdi** [comment]
But Unikey/Laban Key don't use the preedit method like fcitx which need the underline to indicate that you are typing that word.

**Comment by zenfas** [comment]
As you know the habit of Vietnamese, if want more people use, fcitx should hide underline and no popup.
I see ibus-m17n and ibus-bamboo (even method 1) try to hide underline by default

**Comment by zenfas** [comment]
I'm not dev, but I think underline is just output for user, should have technic method to hide it

**Comment by trmdi** [comment]
The underline is a useful thing in the preedit method so I think it's not needed to be hidden and shouldn't. There is nothing wrong with that.

fcitx should always do things properly, not that try to find more users.

**Comment by zenfas** [comment]
Nothing wrong if hide also, normal user don't care about technic, they just want to use it simple and the same they use in other platforms

**Comment by trmdi** [comment]
> Nothing wrong if hide also, normal user don't care about technic, they just want to use it simple and the same they use in other platforms

It's completely wrong.

Btw, Laban Key on Android 12 does show the underline while typing. As a normal Vietnamese typer, I have no issue with it.

**Comment by zenfas** [comment]
Are you sure about Labankey on Android 12, I use it on Poco F3 Android 12, no underline. Maybe you're using Gboard

**Comment by zenfas** [comment]
I don't what's wrong! I don't want to debate here.

**Comment by trmdi** [comment]
> Are you sure about Labankey on Android 12, I use it on Poco F3 Android 12, no underline. Maybe you're using Gboard

![screenshot](https://i.ibb.co/QvngcPK/Screenshot-2022-09-27-10-07-02-904-com-sec-android-app-sbrowser.jpg)

**Comment by zenfas** [comment]
![Screenshot_2022-09-27-10-32-36-913_com vng inputmethod labankey](https://user-images.githubusercontent.com/66258788/192425679-89a7d980-d692-46e2-92de-276a2a61fac4.jpg)
Laban Key have 3 mode in config: no underline, change color or underline. No underline is default on my phone, I don't change anyhing

**Comment by zenfas** [comment]
Thank you @trmdi , can you make the same for fcitx5-bamboo and make hide underline by default like ibus-bamboo.

**Comment by trmdi** [comment]
> Thank you @trmdi , can you make the same for fcitx5-bamboo and make hide underline by default like ibus-bamboo.

Sorry, I only use unikey and the underline should be displayed by default.

**Comment by wengxt** [comment]
@zenfas added in https://github.com/fcitx/fcitx5-bamboo/commit/38cc18bd6e9991beb507a254d7da07d63ad9dd0c
