### ISSUE TITLE
Auto restore not working for `Enter`

### ISSUE THREAD

**Issue by ModProg** [fcitx/fcitx5-unikey#3]
When ending the word with `enter`, Auto restore keys with invalid words, does not work.

This could be by design, to avoid confusion for applications that send on `return`, but maybe it is possible to add a switch?

**Comment by wengxt** [comment]
You may give it a test to see if it works like you expected.

**Comment by ModProg** [comment]
> You may give it a test to see if it works like you expected.

Works as expected now, thanks.
