### ISSUE TITLE
Weird behavior when typing and clicking

### ISSUE THREAD

**Issue by trmdi** [fcitx/fcitx5-unikey#35]
Issue 1: in Kate and Konsole
1. Open Kate, type "a" in line 1 then go to line 2 and type: "a" and don't commit it.
2a. If I click on line 1 and type "s", fcitx should commit the string and insert "s" in line 1, instead of continuing typing on the line 2
2b. If I click on Konsole (maybe any Qt app, not happen when I test with Firefox), the preedit string in the step 1 will be lost. (This is probably fixable by committing when the input lost the focus)

Issue 2: in Firefox
1. Open Firefox and focus in Github's textbox
2. Type "a" in line 1 then type "a" in line 2, don't commit it.
3. go back to line 1 (with your mouse) and type anything, the text doesn't change until you commit it then type another letter.
4. the SurroundingText capability of the context is lost. Detail: https://github.com/fcitx/fcitx5-unikey/issues/35#issuecomment-1341893811

These issues also happen with fcitx5-bamboo.

**Comment by wengxt** [comment]
@trmdi how it works really depends on the toolkit implement it. if you’re using gtk im module, you can use dbus-monitor to see what signal that toolkit sends.

**Comment by wengxt** [comment]
@wengxt sometimes, toolkit may not even or fully support all the signal. the right thing, especially when the widget is not coming from the toolkit itself (e.g. vte as in gtk, kate editor part as in qt). IIRC, kate part doesn’t support invoke action like other qt widget.

**Comment by trmdi** [comment]
Is there any way to detect Mouse click events inside the input while typing? We should commit the preedit whenever there is a mouse click event.

**Comment by wengxt** [comment]
@trmdi qt has an invokeAction method, which is mapped to invokeAction in InputMethodEngine, but also fyi, kate doesn't implement it.

**Comment by zenfas** [comment]
Can we always commit when detect cusor focus out the current textbox?

**Comment by wengxt** [comment]
> Can we always commit when detect cusor focus out the current textbox?

it is what we do today.

**Comment by wengxt** [comment]
That certainly doesn't work for me on wayland.

Also It's a bad idea especially if you are using touchpad.

**Comment by trmdi** [comment]
An additional effect of the Issue 2, after it happened, the SurroundingText capability of the context is lost.
See this screen recording:
![fcitx-2022-12-08_09 22 28](https://user-images.githubusercontent.com/11857205/206341512-e458dfee-d548-4e08-960a-8b27c94e8f5f.gif)

**Comment by wengxt** [comment]
@trmdi with the change in fcitx5-gtk above firefox should be fine now. As for Qt I prefer to fix it in kate/qt. Just like we only apply hack to gtk2/gtk3 but not gtk4.

**Comment by wengxt** [comment]
actually I noticed one thing, that I probably missing for long time. That I never implement QPlatformInputContext::commit, which seems to be the request to commit preedit. This should fix it for non-kate app (or, built-in qt widget).
The final thing should be fix on the kate side.

**Comment by wengxt** [comment]
Patch to add invokeAction and commit preedit to kate: https://invent.kde.org/frameworks/ktexteditor/-/merge_requests/456
