### ISSUE TITLE
LibreOffice Writer Error when turn on "Allow to modify surrounding text" on Xubuntu

### ISSUE THREAD

**Issue by zenfas** [fcitx/fcitx5-unikey#36]
When I turned on "Allow to modify surrounding text", open Libreoffice Writer on Xubuntu, got error 
![Peek Unikey 31012023(1)](https://user-images.githubusercontent.com/66258788/215657444-35d9551f-5dcf-4abb-b558-8dbd86671f63.gif)
 If I turn off Allow.. will be ok

**Comment by zenfas** [comment]
fcitx5-diagnose 
# System Info:
1.  `uname -a`:

        Linux vXubuntu 5.19.0-21-generic #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct 12 18:33:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Ubuntu
        Description:	Ubuntu Lunar Lobster (development branch)
        Release:	23.04
        Codename:	lunar

3.  `lsb_release -d`:

        Description:	Ubuntu Lunar Lobster (development branch)

4.  `/etc/lsb-release`:

        DISTRIB_ID=Ubuntu
        DISTRIB_RELEASE=23.04
        DISTRIB_CODENAME=lunar
        DISTRIB_DESCRIPTION="Ubuntu Lunar Lobster (development branch)"

5.  `/etc/os-release`:

        PRETTY_NAME="Ubuntu Lunar Lobster (development branch)"
        NAME="Ubuntu"
        VERSION_ID="23.04"
        VERSION="23.04 (Lunar Lobster)"
        VERSION_CODENAME=lunar
        ID=ubuntu
        ID_LIKE=debian
        HOME_URL="https://www.ubuntu.com/"
        SUPPORT_URL="https://help.ubuntu.com/"
        BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
        PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
        UBUNTU_CODENAME=lunar
        LOGO=ubuntu-logo

6.  Desktop Environment:

    Desktop environment is `xfce`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.2.2(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0.0'


        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            en_AG
            en_AG.utf8
            en_AU.utf8
            en_BW.utf8
            en_CA.utf8
            en_DK.utf8
            en_GB.utf8
            en_HK.utf8
            en_IE.utf8
            en_IL
            en_IL.utf8
            en_IN
            en_IN.utf8
            en_NG
            en_NG.utf8
            en_NZ.utf8
            en_PH.utf8
            en_SG.utf8
            en_US.utf8
            en_ZA.utf8
            en_ZM
            en_ZM.utf8
            en_ZW.utf8
            POSIX
            vi_VN
            vi_VN.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LANGUAGE=en_US
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC=vi_VN
            LC_TIME=vi_VN
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY=vi_VN
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER=vi_VN
            LC_NAME=vi_VN
            LC_ADDRESS=vi_VN
            LC_TELEPHONE=vi_VN
            LC_MEASUREMENT=vi_VN
            LC_IDENTIFICATION=vi_VN
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/xubuntu

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/xubuntu/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/xubuntu/.config/fcitx5`).

5.  Current user:

    The script is run as xubuntu (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.21`

3.  process:

    Found 2 fcitx5 processes:

            990 fcitx5
           1325 fcitx5-config-q

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.21`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `990`.

    Debug information from dbus:

           Group [x11::0] has 27 InputContext(s)
          IC [a8938edd4ef94c2a997615779a0dfbcb] program:soffice frontend:dbus cap:6000000052 focus:0
          IC [d633ca3d8d314951bb60e97d84bcf7d3] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [b220ad3952724084909d62476577681c] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [41d90e4eb2514d20a571bcf126d34f5d] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [a9f1cf28bc754c4c9ab06eb2680fb080] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [38734c1fe21342e9b4d41bf5748729e6] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [1f174e4c480840cd9be8e2b954314c59] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [cd9f3ae90e8d478396cb3958b2b35082] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [17160a42f78b4b2cbcf6405fb6ddad4e] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [e741aa8f0bed4c8ab93dcbc5ba0ca1a3] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [d964e6878b574e35ad59265863438926] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [d6939bdebe4c4d29a6f0ade2c4eb1dc2] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [1d7ec8d43fe64359ad90e459947a0e90] program:kate frontend:dbus cap:6000800072 focus:0
          IC [41fb465c91d2478c8478a70bd70733fb] program:xfce4-terminal frontend:dbus cap:6000000012 focus:1
          IC [1eb9fbb1ec024a3e892d7b298dd13563] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [d85e78bf786e440c8978f3e9dee8988d] program:fcitx5-config-qt frontend:dbus cap:16000800072 focus:0
          IC [ddbd4a5556024ef09e32131b89d98fc2] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [86c91e85f0be4ca797563e00822272b9] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [69a076503f654e13b45f8a4c1003510e] program:mousepad frontend:dbus cap:6000000052 focus:0
          IC [f0bfbf9a9d9d425880b438b90e53172a] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [84cbfb19c25d49ad9c2ac326c8edee8a] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [6739da0471f2498b8bd6f74264cafbd8] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [56ef1861ae1f47668574073770c81544] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [b514209e47394fa9892ee504825fa51d] program:wrapper-2.0 frontend:dbus cap:6000000052 focus:0
          IC [a5dfb70c72e74a718e9cd6d1039d4544] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [a7c9843688dd42fba63d486c35dc71f8] program:soffice frontend:dbus cap:6000000012 focus:0
          IC [21c56e889e514cec97bff46d75f69603] program:soffice frontend:dbus cap:6000000012 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found fcitx5 im module for qt5: `/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 im module for qt6: `/lib/x86_64-linux-gnu/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx5-unikey-macro-editor.so`.
    Found fcitx5 qt5 module: `/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt5 module: `/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx5-unikey-keymap-editor.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.33

        **Failed to find fcitx5 in immodule cache at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.35` at `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.35

        Found fcitx5 im modules for gtk `3.24.35`.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 23 enabled addons:

            Bamboo Wrapper For Fcitx 1.0.2
            Classic User Interface 5.0.21
            Clipboard 5.0.21
            DBus 5.0.21
            DBus Frontend 5.0.21
            Emoji 5.0.21
            Fcitx4 Frontend 5.0.21
            IBus Frontend 5.0.21
            Input method selector 5.0.21
            Keyboard 5.0.21
            Keyman 1.0.6
            KDE Input Method Panel 5.0.21
            M17N 5.0.11
            Status Notifier 5.0.21
            Notification 5.0.21
            Quick Phrase 5.0.21
            Spell 5.0.21
            Unicode 5.0.21
            Unikey Wrapper For Fcitx 5.0.12
            Wayland 5.0.21
            Wayland Input method frontend 5.0.21
            XCB 5.0.21
            X Input Method Frontend 5.0.21

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel

## Input Methods:
1.  `/home/xubuntu/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=unikey

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=keyman:vietnamese_telex
        # Layout
        Layout=

        [Groups/0/Items/2]
        # Name
        Name=unikey
        # Layout
        Layout=

        [Groups/0/Items/3]
        # Name
        Name=m17n_vi_telex
        # Layout
        Layout=

        [Groups/0/Items/4]
        # Name
        Name=bamboo
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Thứ ba, 31 Tháng 1 năm 2023 10:38:55 +07

2.  `/home/xubuntu/.config/fcitx5/crash.log`:

    `/home/xubuntu/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**
xubuntu@vXubuntu:~$

**Comment by zenfas** [comment]
Unikey  will auto delete space and continue previous word. It  didn't happen on Kate or Mousepad on the same system

cc @trmdi

**Comment by zenfas** [comment]
I tried to build fcitx5, fcitx5-gtk from newest git, still got error @wengxt 

fcitx5-diagnose 
# System Info:
1.  `uname -a`:

        Linux vXubuntu 5.19.0-21-generic #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct 12 18:33:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Ubuntu
        Description:	Ubuntu Lunar Lobster (development branch)
        Release:	23.04
        Codename:	lunar

3.  `lsb_release -d`:

        Description:	Ubuntu Lunar Lobster (development branch)

4.  `/etc/lsb-release`:

        DISTRIB_ID=Ubuntu
        DISTRIB_RELEASE=23.04
        DISTRIB_CODENAME=lunar
        DISTRIB_DESCRIPTION="Ubuntu Lunar Lobster (development branch)"

5.  `/etc/os-release`:

        PRETTY_NAME="Ubuntu Lunar Lobster (development branch)"
        NAME="Ubuntu"
        VERSION_ID="23.04"
        VERSION="23.04 (Lunar Lobster)"
        VERSION_CODENAME=lunar
        ID=ubuntu
        ID_LIKE=debian
        HOME_URL="https://www.ubuntu.com/"
        SUPPORT_URL="https://help.ubuntu.com/"
        BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
        PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
        UBUNTU_CODENAME=lunar
        LOGO=ubuntu-logo

6.  Desktop Environment:

    Desktop environment is `xfce`.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.2.15(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0.0'


        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locales:

            C
            C.utf8
            en_AG
            en_AG.utf8
            en_AU.utf8
            en_BW.utf8
            en_CA.utf8
            en_DK.utf8
            en_GB.utf8
            en_HK.utf8
            en_IE.utf8
            en_IL
            en_IL.utf8
            en_IN
            en_IN.utf8
            en_NG
            en_NG.utf8
            en_NZ.utf8
            en_PH.utf8
            en_SG.utf8
            en_US.utf8
            en_ZA.utf8
            en_ZM
            en_ZM.utf8
            en_ZW.utf8
            POSIX
            vi_VN
            vi_VN.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LANGUAGE=en_US
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC=vi_VN
            LC_TIME=vi_VN
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY=vi_VN
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER=vi_VN
            LC_NAME=vi_VN
            LC_ADDRESS=vi_VN
            LC_TELEPHONE=vi_VN
            LC_MEASUREMENT=vi_VN
            LC_IDENTIFICATION=vi_VN
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/xubuntu

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/xubuntu/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/xubuntu/.config/fcitx5`).

5.  Current user:

    The script is run as xubuntu (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.22`

3.  process:

    Found 2 fcitx5 processes:

            973 fcitx5
           1305 fcitx5-config-q

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.23`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `973`.

    Debug information from dbus:

           Group [x11::0] has 3 InputContext(s)
          IC [d4862744336f46ac8087272e56f4a94c] program:xfce4-terminal frontend:dbus cap:6000000032 focus:1
          IC [92e1a071cee54819a6a59ae5035bcaf5] program:wrapper-2.0 frontend:dbus cap:6000000072 focus:0
          IC [f679c4ee963d40e39240f6813edcc8cf] program:fcitx5-config-qt frontend:dbus cap:16000800072 focus:0
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.


3.  Qt IM module files:

    Found fcitx5 im module for qt5: `/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 im module for qt6: `/lib/x86_64-linux-gnu/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found fcitx5 qt5 module: `/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx5-unikey-macro-editor.so`.
    Found fcitx5 qt5 module: `/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 qt5 module: `/lib/x86_64-linux-gnu/fcitx5/qt5/libfcitx5-unikey-keymap-editor.so`.

    Following error may not be accurate because guessing Qt version from path depends on how your distribution packages Qt. It is not a critical error if you do not use any Qt application with certain version of Qt or you are using text-input support by Qt under Wayland.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.33

        **Failed to find fcitx5 in immodule cache at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.36` at `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.36

        Found fcitx5 im modules for gtk `3.24.36`.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx5.so" 
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*" 

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 23 enabled addons:

            Bamboo Wrapper For Fcitx 1.0.2
            Classic User Interface 5.0.22
            Clipboard 5.0.22
            DBus 5.0.22
            DBus Frontend 5.0.22
            Emoji 5.0.22
            Fcitx4 Frontend 5.0.22
            IBus Frontend 5.0.22
            Input method selector 5.0.22
            Keyboard 5.0.22
            Keyman 1.0.6
            KDE Input Method Panel 5.0.22
            M17N 5.0.11
            Status Notifier 5.0.22
            Notification 5.0.22
            Quick Phrase 5.0.22
            Spell 5.0.22
            Unicode 5.0.22
            Unikey Wrapper For Fcitx 5.0.12
            Wayland 5.0.22
            Wayland Input method frontend 5.0.22
            XCB 5.0.22
            X Input Method Frontend 5.0.22

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel

## Input Methods:
1.  `/home/xubuntu/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=unikey

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=keyman:vietnamese_telex
        # Layout
        Layout=

        [Groups/0/Items/2]
        # Name
        Name=unikey
        # Layout
        Layout=

        [Groups/0/Items/3]
        # Name
        Name=m17n_vi_telex
        # Layout
        Layout=

        [Groups/0/Items/4]
        # Name
        Name=bamboo
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Thứ năm, 02 Tháng 2 năm 2023 09:34:08 +07

2.  `/home/xubuntu/.config/fcitx5/crash.log`:

    `/home/xubuntu/.config/fcitx5/crash.log` not found.

**Comment by zenfas** [comment]
This one doesn't happen on Kubuntu

**Comment by zenfas** [comment]
Don't have issue with ibus-bamboo (choose Surrounding mode), ibus-keyman or fcitx5-keyman. Does error belong to fxcitx5-unikey itself @wengxt ?

**Comment by trmdi** [comment]
> This one doesn't happen on Kubuntu

What are versions of packages?

**Comment by zenfas** [comment]
> > This one doesn't happen on Kubuntu
> 
> What are versions of packages?

On KDE, Libreoffice uses QT; on XFCE, it uses GTK

**Comment by trmdi** [comment]
> > > This one doesn't happen on Kubuntu
> > 
> > 
> > What are versions of packages?
> 
> On KDE, Libreoffice uses QT; on XFCE, it uses GTK

Ah yes, Libreoffice with kf5 vcl hasn't supported surroundingText yet: https://bugs.documentfoundation.org/show_bug.cgi?id=152519

**Comment by zenfas** [comment]
But with ibus-bamboo (changed to surrounding mode) and ibus-keyman (which I know use surrouding only), issue not happen

**Comment by zenfas** [comment]
@trmdi ibus-bamboo with surrounding mode works fine on LibreOffice on gtk environment (Gnome, MATE, XFCE). So I think problem belong to fcitx5-unikey or fcitx5

**Comment by zenfas** [comment]
Just tested on Ubuntu Mate daily live 24.04

**Comment by wengxt** [comment]
Please explain what key you used to type

**Comment by zenfas** [comment]
@wengxt  Type "Gox" => "Gõ", press **spacebar**, type "t", but after type t, **space was deleted**, become "Gõt", instead "Gõ t"

**Comment by wengxt** [comment]
I observed the surrounding text returned from ibus and fcitx and they are the same.
The issue is libreoffice surrounding text does not return the suffix space. No matter how many space you type, surrounding text does not include the space, until there's another non-space character.

Next, the surrounding text mode in ibus-bamboo and fcitx5-unikey are different. fcitx5-unikey allow you to move cursor and continue to type a word. ibus-bamboo is just using surrounding text as a replacement to maintain the preedit state. They are totally different feature.

From what I see, fcitx is doing everything as expected, the bug is in libreoffice.

**Comment by zenfas** [comment]
@wengxt can you help me make issue on LibreOffice (gtk only, qt work normal), I don't how to explain detail for them about technical. Thank you
