### ISSUE TITLE
Enable spell check and Restore invalid words by default

### ISSUE THREAD

**Issue by trmdi** [fcitx/fcitx5-unikey#7]
I use it daily so I know these ones should be enabled by default.

Test words: when, word...

When being not enabled: ưhen, ửod
When being enabled: when, word

**Comment by wengxt** [comment]
I can understand that this could be useful when people want to type English directly when using Unikey. As Chinese we also commonly type English directly in Pinyin mode. 

But I checked other platform like m17n, win and ios. None of them have this behavior by default. The closest one on iOS also have a "spell check", though I can't reproduce a similar behavior.

I notice the bundled Vietnamese input method on Windows seems to be pretty poor (no configuration option), is there any more popular third party ones that's being used that has this behavior?

I tried to search on the Google and from a "Lahan Key" that seems to have this feature by default. Is that a popular one on mobile?

**Comment by trmdi** [comment]
Yes, Laban key is the best input method on Android.
